// authentication actions
export const SIGN_IN_INIT = "SIGN_IN_INIT";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL = "SIGN_IN_FAIL";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_IN_INIT = "REFRESH_TOKEN_IN_INIT";
export const REFRESH_TOKEN_FAIL = "REFRESH_TOKEN_FAIL";
export const REQUEST_LIST_SUCCESS = "REQUEST_LIST_SUCCESS";
export const REQUEST_LIST_COUNT_SUCCESS = "REQUEST_LIST_COUNT_SUCCESS";
export const REQUEST_LIST_FAIL = "REQUEST_LIST_FAIL";
export const REQUEST_LIST_COUNT_FAIL = "REQUEST_LIST_COUNT_FAIL";
export const SIGN_OUT = "SIGN_OUT";
export const SIGN_UP_INIT = "SIGN_UP_INIT";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";
export const SOMETHINGWENTWRONG = "SOMETHINGWENTWRONG";
export const SOMETHINGWENTWRONGREMOVE = "SOMETHINGWENTWRONGREMOVE";
export const VALIDATE_EMAIL_ADDRESS_SUCCES = "VALIDATE_EMAIL_ADDRESS_SUCCES";
export const VALIDATE_EMAIL_ADDRESS_FAIL = "VALIDATE_EMAIL_ADDRESS_FAIL";
export const VALIDATE_EMAIL_AND_PASSWORD_SUCCES = "VALIDATE_EMAIL_AND_PASSWORD_SUCCES";
export const VALIDATE_EMAIL_AND_PASSWORD_FAIL = "VALIDATE_EMAIL_AND_PASSWORD_FAIL";
export const VALIDATE_EMAIL_ADDRESS_INIT = "VALIDATE_EMAIL_ADDRESS_INIT";
export const VALIDATE_EMAIL_AND_PASSWORD_INIT = "VALIDATE_EMAIL_AND_PASSWORD_INIT";
export const SAVE_USER_REQUEST_INIT = "SAVE_USER_REQUEST_INIT";
export const REQUEST_LIST_INIT = "REQUEST_LIST_INIT";
export const CLEARE_STATE_INIT = "CLEARE_STATE_INIT";
export const CLEARE_STATE_BACKBUTTON_INIT = "CLEARE_STATE_BACKBUTTON_INIT";
export const RESET_RESPONSEMESSAGE_STATE = "RESET_RESPONSEMESSAGE_STATE";
export const ROUTING_DATA = "ROUTING_DATA";

// FOR ACTIVATE TABS
export const MAKE_TAB_ACTIVE_INIT = "MAKE_TAB_ACTIVE_INIT";
// for get all user role
export const GET_ALL_USER_DATA_INIT = "GET_ALL_USER_DATA_INIT";
export const GET_ALL_USER_DATA_SUCCESS = "GET_ALL_USER_DATA_SUCCESS";
export const GET_ALL_USER_DATA_FAIL = "GET_ALL_USER_DATA_FAIL";



//NOTIFICATIONs
export const NOTIFICATION = "NOTIFICATION";
// export const FIND_CUSTOMER_FROM_MISYS_INIT = "FIND_CUSTOMER_FROM_MISYS_INIT";
export const RESET_STATE = "RESET_STATE";
// export const FIND_CUSTOMER_FROM_MISYS_SUCCESS = "FIND_CUSTOMER_FROM_MISYS_SUCCESS";
// export const FIND_CUSTOMER_FROM_MISYS_FAIL = "FIND_CUSTOMER_FROM_MISYS_FAIL";

// export const FIND_CUSTOMER_ACCOUNT_DETAILS_FROM_MYSIS_INIT = "FIND_CUSTOMER_ACCOUNT_DETAILS_FROM_MYSIS_INIT";
// export const FIND_CUSTOMER_ACCOUNT_DETAILS_FROM_MYSIS_SUCCESS = "FIND_CUSTOMER_ACCOUNT_DETAILS_FROM_MYSIS_SUCCESS";
// export const FIND_CUSTOMER_ACCOUNT_DETAILS_FROM_MYSIS_FAIL = "FIND_CUSTOMER_ACCOUNT_DETAILS_FROM_MYSIS_FAIL";

// export const ADD_WRITE_OFF_INIT = "ADD_WRITE_OFF_INIT";
// export const ADD_WRITE_OFF_SUCCESS = "ADD_WRITE_OFF_SUCESS";
// export const ADD_WRITE_OFF_FAIL = "ADD_WRITE_OFF_FAIL";

//approvalscount
export const GET_APPROVALS_COUNT_INIT = "GET_APPROVALS_COUNT_INIT";
export const GET_APPROVALS_COUNT_SUCCESS = "GET_APPROVALS_COUNT_SUCCESS";
export const GET_APPROVALS_COUNT_FAIL = "GET_APPROVALS_COUNT_FAIL";
export const SAVE_USER_REQUEST_SUCCESS = "SAVE_USER_REQUEST_SUCCESS";
export const SAVE_USER_REQUEST_FAIL = "SAVE_USER_REQUEST_FAIL";



//approvals
export const GET_APPROVALS_INIT = "GET_APPROVALS_INIT";
export const GET_APPROVALS_SUCCESS = "GET_APPROVALS_SUCCESS";
export const GET_APPROVALS_FAIL = "GET_APPROVALS_FAIL";

//Save approvals
export const SAVE_APPROVALS_INIT = "SAVE_APPROVALS_INIT";
export const SAVE_APPROVALS_SUCCESS = "SAVE_APPROVALS_SUCCESS";
export const SAVE_APPROVALS_FAIL = "SAVE_APPROVALS_FAIL";

//view write off
// export const VIEW_WRITE_OFF_INIT = "VIEW_WRITE_OFF_INIT";
// export const VIEW_WRITE_OFF_SUCCESS = "VIEW_WRITE_OFF_SUCCESS";
// export const VIEW_WRITE_OFF_FAIL = "VIEW_WRITE_OFF_FAIL";
export const NULL_STATE = "NULL_STATE"
//listofwriteoff
// export const LIST_WRITE_OFF_INIT = "LIST_WRITE_OFF_INIT";
// export const LIST_WRITE_OFF_SUCCESS = "LIST_WRITE_OFF_SUCCESS";
// export const LIST_WRITE_OFF_FAIL = "LIST_WRITE_OFF_FAIL";
//Editofwriteoff
// export const EDIT_WRITE_OFF_INIT = "EDIT_WRITE_OFF_INIT";
// export const EDIT_WRITE_OFF_SUCCESS = "EDIT_WRITE_OFF_SUCCESS";
// export const EDIT_WRITE_OFF_FAIL = "EDIT_WRITE_OFF_FAIL";
//Deleteofwriteoff
// export const DELETE_WRITE_OFF_INIT = "DELETE_WRITE_OFF_INIT";
// export const DELETE_WRITE_OFF_SUCCESS = "DELETE_WRITE_OFF_SUCCESS";
// export const DELETE_WRITE_OFF_FAIL = "DELETE_WRITE_OFF_FAIL";

//view approvals
export const VIEW_APPROVAL_HISTORY_INIT = "VIEW_APPROVAL_HISTORY_INIT";
export const VIEW_APPROVAL_HISTORY_SUCCESS = "VIEW_APPROVAL_HISTORY_SUCCESS";
export const VIEW_APPROVAL_HISTORY_FAIL = "VIEW_APPROVAL_HISTORY_FAIL";

// complete report

export const COMPLETE_REPORT_INIT = "COMPLETE_REPORT_INIT";
export const COMPLETE_REPORT_SUCCESS = "COMPLETE_REPORT_SUCCESS";
export const COMPLETE_REPORT_FAIL = "COMPLETE_REPORT_FAIL";

// credit policy report

export const CREDIT_POLICY_REPORT_INIT = "CREDIT_POLICY_REPORT_INIT";
export const CREDIT_POLICY_REPORT_SUCCESS = "CREDIT_POLICY_REPORT_SUCCESS";
export const CREDIT_POLICY_REPORT_FAIL = "CREDIT_POLICY_REPORT_FAIL";

// balance sheet report

export const BALANCE_SHEET_REPORT_INIT = "BALANCE_SHEET_REPORT_INIT";
export const BALANCE_SHEET_REPORT_SUCCESS = "BALANCE_SHEET_REPORT_SUCCESS";
export const BALANCE_SHEET_REPORT_FAIL = "BALANCE_SHEET_REPORT_FAIL";



// UPload Document 

export const UPLOAD_DOCUMNET_FILE_SUCCESS = "UPLOAD_DOCUMNET_FILE_SUCCESS";
export const RESET_ALL_STATE_REPORTS = "RESET_ALL_STATE_REPORTS";


// UI
export const UI_GO_BACK_ENABLE = "UI_GO_BACK_ENABLE";
export const UI_GO_BACK_DISABLE = "UI_GO_BACK_DISABLE";
export const HIDE = "HIDE";
export const SHOW = "SHOW";

// SETUP FORMS ACTION TYPES:
export const GET_SETUP_FORM_INIT = "GET_SETUP_FORM_INIT";
export const GET_SETUP_FORM_FAIL = "GET_SETUP_FORM_FAIL";
export const GET_BORROWER_TYPE_INIT = "GET_BORROWER_TYPE_INIT";
export const GET_BORROWER_TYPE_SUCCESS = "GET_BORROWER_TYPE_SUCCESS";
export const GET_BORROWER_TYPE_FAIL = "GET_BORROWER_TYPE_FAIL";

export const ADD_BORROWER_TYPE_INIT = "ADD_BORROWER_TYPE_INIT";
export const ADD_BORROWER_TYPE_SUCCESS = "ADD_BORROWER_TYPE_SUCCESS";
export const ADD_BORROWER_TYPE_FAIL = "ADD_BORROWER_TYPE_FAIL";

export const UPDATE_BORROWER_TYPE_INIT = "UPDATE_BORROWER_TYPE_INIT";
export const UPDATE_BORROWER_TYPE_SUCCESS = "UPDATE_BORROWER_TYPE_SUCCESS";
export const UPDATE_BORROWER_TYPE_FAIL = "UPDATE_BORROWER_TYPE_FAIL";

export const DELETE_BORROWER_TYPE_INIT = "DELETE_BORROWER_TYPE_INIT";
export const DELETE_BORROWER_TYPE_SUCCESS = "DELETE_BORROWER_TYPE_SUCCESS";
export const DELETE_BORROWER_TYPE_FAIL = "DELETE_BORROWER_TYPE_FAIL";


export const GET_ADVANCE_CLASSIFICATION_INIT = "GET_ADVANCE_CLASSIFICATION_INIT";
export const GET_ADVANCE_CLASSIFICATION_SUCCESS = "GET_ADVANCE_CLASSIFICATION_SUCCESS";
export const GET_ADVANCE_CLASSIFICATION_FAIL = "GET_ADVANCE_CLASSIFICATION_FAIL";

export const ADD_ADVANCE_CLASSIFICATION_INIT = "ADD_ADVANCE_CLASSIFICATION_INIT";
export const ADD_ADVANCE_CLASSIFICATION_SUCCESS = "ADD_ADVANCE_CLASSIFICATION_SUCCESS";
export const ADD_ADVANCE_CLASSIFICATION_FAIL = "ADD_ADVANCE_CLASSIFICATION_FAIL";

export const UPDATE_ADVANCE_CLASSIFICATION_INIT = "UPDATE_ADVANCE_CLASSIFICATION_INIT";
export const UPDATE_ADVANCE_CLASSIFICATION_SUCCESS = "UPDATE_ADVANCE_CLASSIFICATION_SUCCESS";
export const UPDATE_ADVANCE_CLASSIFICATION_FAIL = "UPDATE_ADVANCE_CLASSIFICATION_FAIL";

export const DELETE_ADVANCE_CLASSIFICATION_INIT = "DELETE_ADVANCE_CLASSIFICATION_INIT";
export const DELETE_ADVANCE_CLASSIFICATION_SUCCESS = "DELETE_ADVANCE_CLASSIFICATION_SUCCESS";
export const DELETE_ADVANCE_CLASSIFICATION_FAIL = "DELETE_ADVANCE_CLASSIFICATION_FAIL";

export const GET_MANAGEMENT_UNIT_INIT = "GET_MANAGEMENT_UNIT_INIT";
export const GET_MANAGEMENT_UNIT_SUCCESS = "GET_MANAGEMENT_UNIT_SUCCESS";
export const GET_MANAGEMENT_UNIT_FAIL = "GET_MANAGEMENT_UNIT_FAIL";

export const ADD_MANAGEMENT_UNIT_INIT = "ADD_MANAGEMENT_UNIT_INIT";
export const ADD_MANAGEMENT_UNIT_SUCCESS = "ADD_MANAGEMENT_UNIT_SUCCESS";
export const ADD_MANAGEMENT_UNIT_FAIL = "ADD_MANAGEMENT_UNIT_FAIL";

export const UPDATE_MANAGEMENT_UNIT_INIT = "UPDATE_MANAGEMENT_UNIT_INIT";
export const UPDATE_MANAGEMENT_UNIT_SUCCESS = "UPDATE_MANAGEMENT_UNIT_SUCCESS";
export const UPDATE_MANAGEMENT_UNIT_FAIL = "UPDATE_MANAGEMENT_UNIT_FAIL";

export const DELETE_MANAGEMENT_UNIT_INIT = "DELETE_MANAGEMENT_UNIT_INIT";
export const DELETE_MANAGEMENT_UNIT_SUCCESS = "DELETE_MANAGEMENT_UNIT_SUCCESS";
export const DELETE_MANAGEMENT_UNIT_FAIL = "DELETE_MANAGEMENT_UNIT_FAIL";


export const GET_NATURE_OF_CHARGE_INIT = "GET_NATURE_OF_CHARGE_INIT"
export const GET_NATURE_OF_CHARGE_SUCCESS = "GET_NATURE_OF_CHARGE_SUCCESS"
export const GET_NATURE_OF_CHARGE_DELETE = "GET_NATURE_OF_CHARGE_DELETE"

export const GET_NATURE_OF_SECURITY_INIT = "GET_NATURE_OF_SECURITY_INIT"
export const GET_NATURE_OF_SECURITY_SUCCESS = "GET_NATURE_OF_SECURITY_SUCCESS"
export const GET_NATURE_OF_SECURITY_DELETE = "GET_NATURE_OF_SECURITY_DELETE"

export const GET_WRITEOFFREASON_INIT = "GET_WRITEOFFREASON_INIT"
export const GET_WRITEOFFREASON_SUCCESS = "GET_WRITEOFFREASON_SUCCESS"
export const GET_WRITEOFFREASON_DELETE = "GET_WRITEOFFREASON_DELETE"

export const GET_APPROVAL_REASON_INIT = "GET_APPROVAL_REASON_INIT";
export const GET_APPROVAL_REASON_SUCCESS = "GET_APPROVAL_REASON_SUCCESS";
export const GET_APPROVAL_REASON_FAIL = "GET_APPROVAL_REASON_FAIL";

export const GET_REJECTION_REASON_INIT = "GET_REJECTION_REASON_INIT";
export const GET_REJECTION_REASON_SUCCESS = "GET_REJECTION_REASON_SUCCESS";
export const GET_REJECTION_REASON_FAIL = "GET_REJECTION_REASON_FAIL";

export const GET_APPROVAL_FLOW_INIT = "GET_APPROVAL_FLOW_INIT";
export const GET_APPROVAL_FLOW_SUCCESS = "GET_APPROVAL_FLOW_SUCCESS";
export const GET_APPROVAL_FLOW_FAIL = "GET_APPROVAL_FLOW_FAIL";

export const GET_APPROVAL_FLOW_FOR_EDIT_SUCCESS = "GET_APPROVAL_FLOW_FOR_EDIT_SUCCESS";
export const ACTIONS_APPROVAL_FLOW_FOR_EDIT_SUCCESS = "ACTIONS_APPROVAL_FLOW_FOR_EDIT_SUCCESS";
export const DOWNLOAD_EXCEL_FILE_INIT = "DOWNLOAD_EXCEL_FILE_INIT";
export const DOWNLOAD_EXCEL_FILE_SUCESS = "DOWNLOAD_EXCEL_FILE_SUCCESS";
export const DOWNLOAD_EXCEL_FILE_FAIL_INIT = "DOWNLOAD_EXCEL_FILE_FAIL_INIT";

export const LIST_OFF_PENDING_AND_APPROVED_CASES_SUCCESS = "LIST_OFF_PENDING_AND_APPROVED_CASES_SUCCESS";
export const LIST_OFF_PENDING_AND_APPROVED_CASES_FAIL = "LIST_OFF_PENDING_AND_APPROVED_CASES_FAIL";


export const ACTIVE_EDIT = "ACTIVE_EDIT";
export const ACTIVE_TAB = "ACTIVE_TAB";
export const CLOSED_TAB = "CLOSED_TAB";

export const UPLOAD_LIST = "UPLOAD_LIST";

export const GET_FRAUD_UNIT_INIT = "GET_FRAUD_UNIT_INIT";
export const GET_FRAUD_UNIT_SUCCESS = "GET_FRAUD_UNIT_SUCCESS";
export const GET_FRAUD_UNIT_FAIL = "GET_FRAUD_UNIT_FAIL";

export const GET_SOURCE_UNIT_INIT = "GET_SOURCE_UNIT_INIT";
export const GET_SOURCE_UNIT_SUCCESS = "GET_SOURCE_UNIT_SUCCESS";
export const GET_SOURCE_UNIT_FAIL = "GET_SOURCE_UNIT_FAIL";

export const GET_INDIVIDUALINVOLVED_UNIT_INIT = "GET_INDIVIDUALINVOLVED_UNIT_INIT";
export const GET_INDIVIDUALINVOLVED_UNIT_SUCCESS = "GET_INDIVIDUALINVOLVED_UNIT_SUCCESS";
export const GET_INDIVIDUALINVOLVED_UNIT_FAIL = "GET_INDIVIDUALINVOLVED_UNIT_FAIL";

export const GET_CHANNEL_UNIT_INIT = "GET_CHANNEL_UNIT_INIT";
export const GET_CHANNEL_UNIT_SUCCESS = "GET_CHANNEL_UNIT_SUCCESS";
export const GET_CHANNEL_UNIT_FAIL = "GET_CHANNEL_UNIT_FAIL";

export const GET_FRAUDNOTAFRAUD_UNIT_INIT = "GET_FRAUDNOTAFRAUD_UNIT_INIT";
export const GET_FRAUDNOTAFRAUD_UNIT_SUCCESS = "GET_FRAUDNOTAFRAUD_UNIT_SUCCESS";
export const GET_FRAUDNOTAFRAUD_UNIT_FAIL = "GET_FRAUDNOTAFRAUD_UNIT_FAIL";

export const GET_COMPANYSEGMENT_UNIT_INIT = "GET_COMPANYSEGMENT_UNIT_INIT";
export const GET_COMPANYSEGMENT_UNIT_SUCCESS = "GET_COMPANYSEGMENT_UNIT_SUCCESS";
export const GET_COMPANYSEGMENT_UNIT_FAIL = "GET_COMPANYSEGMENT_UNIT_FAIL";

export const GET_FORGEDDOCUMENTS_UNIT_INIT = "GET_FORGEDDOCUMENTS_UNIT_INIT";
export const GET_FORGEDDOCUMENTS_UNIT_SUCCESS = "GET_FORGEDDOCUMENTS_UNIT_SUCCESS";
export const GET_FORGEDDOCUMENTS_UNIT_FAIL = "GET_FORGEDDOCUMENTS_UNIT_FAIL";

export const GET_SOURCEOFIBCHANNELCREATION_UNIT_INIT = "GET_SOURCEOFIBCHANNELCREATION_UNIT_INIT";
export const GET_SOURCEOFIBCHANNELCREATION_UNIT_SUCCESS = "GET_SOURCEOFIBCHANNELCREATION_UNIT_SUCCESS";
export const GET_SOURCEOFIBCHANNELCREATION_UNIT_FAIL = "GET_SOURCEOFIBCHANNELCREATION_UNIT_FAIL";

export const GET_CITY_UNIT_INIT = "GET_CITY_UNIT_INIT";
export const GET_CITY_UNIT_SUCCESS = "GET_CITY_UNIT_SUCCESS";
export const GET_CITY_UNIT_FAIL = "GET_CITY_UNIT_FAIL";

export const GET_REGION_UNIT_INIT = "GET_REGION_UNIT_INIT";
export const GET_REGION_UNIT_SUCCESS = "GET_REGION_UNIT_SUCCESS";
export const GET_REGION_UNIT_FAIL = "GET_REGION_UNIT_FAIL";

export const GET_CITYANDREGIONMAPPING_UNIT_INIT = "GET_CITYANDREGIONMAPPING_UNIT_INIT";
export const GET_CITYANDREGIONMAPPING_UNIT_SUCCESS = "GET_CITYANDREGIONMAPPING_UNIT_SUCCESS";
export const GET_CITYANDREGIONMAPPING_UNIT_FAIL = "GET_CITYANDREGIONMAPPING_UNIT_FAIL";

export const GET_USERROLES_UNIT_INIT = "GET_USERROLES_UNIT_INIT";
export const GET_USERROLES_UNIT_SUCCESS = "GET_USERROLES_UNIT_SUCCESS";
export const GET_USERROLES_UNIT_FAIL = "GET_USERROLES_UNIT_FAIL";

export const GET_ESCALATIONMATRIX_UNIT_INIT = "GET_ESCALATIONMATRIX_UNIT_INIT";
export const GET_ESCALATIONMATRIX_UNIT_SUCCESS = "GET_ESCALATIONMATRIX_UNIT_SUCCESS";
export const GET_ESCALATIONMATRIX_UNIT_FAIL = "GET_ESCALATIONMATRIX_UNIT_FAIL";

export const GET_APPROVALREASONS_UNIT_INIT = "GET_APPROVALREASONS_UNIT_INIT";
export const GET_APPROVALREASONS_UNIT_SUCCESS = "GET_APPROVALREASONS_UNIT_SUCCESS";
export const GET_APPROVALREASONS_UNIT_FAIL = "GET_APPROVALREASONS_UNIT_FAIL";

export const GET_REJECTIONREASONS_UNIT_INIT = "GET_REJECTIONREASONS_UNIT_INIT";
export const GET_REJECTIONREASONS_UNIT_SUCCESS = "GET_REJECTIONREASONS_UNIT_SUCCESS";
export const GET_REJECTIONREASONS_UNIT_FAIL = "GET_REJECTIONREASONS_UNIT_FAIL";

//Investigation OFficer
export const GET_INVESTIGATION_OFFICER_INIT = "GET_INVESTIGATION_OFFICER_INIT";
export const GET_INVESTIGATION_OFFICER_FAIL = "GET_INVESTIGATION_OFFICER_FAIL";

export const GET_TRANSACTIONDETAILSBYCNIC_UNIT_INIT = "GET_TRANSACTIONDETAILSBYCNIC_UNIT_INIT";
export const GET_TRANSACTIONDETAILSBYCNIC_UNIT_SUCCESS = "GET_TRANSACTIONDETAILSBYCNIC_UNIT_SUCCESS";
export const GET_TRANSACTIONDETAILSBYCNIC_UNIT_FAIL = "GET_TRANSACTIONDETAILSBYCNIC_UNIT_FAIL";

export const GET_CREDITCARDDISPUTE_UNIT_INIT = "GET_CREDITCARDDISPUTE_UNIT_INIT";
export const GET_CREDITCARDDISPUTE_UNIT_SUCCESS = "GET_CREDITCARDDISPUTE_UNIT_SUCCESS";
export const GET_CREDITCARDDISPUTE_UNIT_FAIL = "GET_CREDITCARDDISPUTE_UNIT_FAIL";

export const SEARCH_CREDITCARDDISPUTE_UNIT_INIT = "SEARCH_CREDITCARDDISPUTE_UNIT_INIT";
export const SEARCH_CREDITCARDDISPUTE_UNIT_SUCCESS = "SEARCH_CREDITCARDDISPUTE_UNIT_SUCCESS";
export const SEARCH_CREDITCARDDISPUTE_UNIT_FAIL = "SEARCH_CREDITCARDDISPUTE_UNIT_FAIL";
export const RESET_CREDITCARDDISPUTE_UNIT_SUCCESS = "RESET_CREDITCARDDISPUTE_UNIT_SUCCESS";

export const GET_DISPUTESTATUSCC_UNIT_SUCCESS = "GET_DISPUTESTATUSCC_UNIT_SUCCESS";
export const GET_DISPUTESTATUSCC_UNIT_FAIL = "GET_DISPUTESTATUSCC_UNIT_FAIL";

export const GET_DISPUTESTATUSDC_UNIT_SUCCESS = "GET_DISPUTESTATUSDC_UNIT_SUCCESS";
export const GET_DISPUTESTATUSDC_UNIT_FAIL = "GET_DISPUTESTATUSDC_UNIT_FAIL";

export const GET_DISPUTESTATUSADC_UNIT_SUCCESS = "GET_DISPUTESTATUSADC_UNIT_SUCCESS";
export const GET_DISPUTESTATUSADC_UNIT_FAIL = "GET_DISPUTESTATUSADC_UNIT_FAIL";

export const GET_DISPUTESTATUSBBK_UNIT_SUCCESS = "GET_DISPUTESTATUSBBK_UNIT_SUCCESS";
export const GET_DISPUTESTATUSBBK_UNIT_FAIL = "GET_DISPUTESTATUSBBK_UNIT_FAIL";

export const GET_TRANSACTIONDETAILSBYCNICCC_UNIT_INIT = "GET_TRANSACTIONDETAILSBYCNIC_UNIT_INIT";
export const GET_TRANSACTIONDETAILSBYCNICCC_UNIT_SUCCESS = "GET_TRANSACTIONDETAILSBYCNIC_UNIT_SUCCESS";
export const GET_TRANSACTIONDETAILSBYCNICCC_UNIT_FAIL = "GET_TRANSACTIONDETAILSBYCNIC_UNIT_FAIL";

export const SET_MODAL_FOR_CREDITCARD_DISPUTE = "SET_MODAL_FOR_CREDITCARD_DISPUTE";


export const GET_CREDITCARDDISPUTE_BY_CNIC_UNIT_INIT = "GET_CREDITCARDDISPUTE_BY_CNIC_UNIT_INIT";
export const GET_CREDITCARDDISPUTE_BY_CNIC_UNIT_SUCCESS = "GET_CREDITCARDDISPUTE_BY_CNIC_UNIT_SUCCESS";
export const GET_CREDITCARDDISPUTE_BY_CNIC_UNIT_FAIL = "GET_CREDITCARDDISPUTE_BY_CNIC_UNIT_FAIL";

export const RESET_CREDITCARD_DISPUTE = "RESET_CREDITCARD_DISPUTE";
export const SET_MODAL_FOR_NEGATIVEDATABASE = "SET_MODAL_FOR_NEGATIVEDATABASE";

//for save negativedatabase 
export const GET_NEGATIVEDATABASE_INIT="GET_NEGATIVEDATABASE_INIT";
export const GET_NEGATIVEDATABASE_SUCCESS="GET_NEGATIVEDATABASE_SUCCESS";
export const GET_NEGATIVEDATABASE_FAIL="GET_NEGATIVEDATABASE_FAIL";


export const GET_CREDITCARDDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_INIT = "GET_CREDITCARDDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_INIT";
export const GET_CREDITCARDDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_SUCCESS = "GET_CREDITCARDDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_SUCCESS";
export const GET_CREDITCARDDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_FAIL = "GET_CREDITCARDDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_FAIL";

export const UPDATE_CREDITCARDDISPUTE_UNIT_INIT = "UPDATE_CREDITCARDDISPUTE_UNIT_INIT";
export const UPDATE_CREDITCARDDISPUTE_UNIT_SUCCESS = "UPDATE_CREDITCARDDISPUTE_UNIT_SUCCESS";
export const UPDATE_CREDITCARDDISPUTE_UNIT_FAIL = "UPDATE_CREDITCARDDISPUTE_UNIT_FAIL";

export const UPDATEANDAPPROVE_CREDITCARDDISPUTE_UNIT_INIT = "UPDATEANDAPPROVE_CREDITCARDDISPUTE_UNIT_INIT";
export const UPDATEANDAPPROVE_CREDITCARDDISPUTE_UNIT_SUCCESS = "UPDATEANDAPPROVE_CREDITCARDDISPUTE_UNIT_SUCCESS";
export const UPDATEANDAPPROVE_CREDITCARDDISPUTE_UNIT_FAIL = "UPDATEANDAPPROVE_CREDITCARDDISPUTE_UNIT_FAIL";

export const SEARCH_DEBITCARDDISPUTE_UNIT_INIT = "SEARCH_DEBITCARDDISPUTE_UNIT_INIT";
export const SEARCH_DEBITCARDDISPUTE_UNIT_SUCCESS = "SEARCH_DEBITCARDDISPUTE_UNIT_SUCCESS";
export const SEARCH_DEBITCARDDISPUTE_UNIT_FAIL = "SEARCH_DEBITCARDDISPUTE_UNIT_FAIL";

export const RESET_DEBITCARD_DISPUTE = "RESET_DEBITCARD_DISPUTE";

export const SET_MODAL_FOR_DEBITCARD_DISPUTE = "SET_MODAL_FOR_DEBITCARD_DISPUTE";

export const GET_CUSTOMERBYCNIC_UNIT_INIT = "GET_CUSTOMERBYCNIC_UNIT_INIT";
export const GET_CUSTOMERBYCNIC_UNIT_SUCCESS = "GET_CUSTOMERBYCNIC_UNIT_SUCCESS";
export const GET_CUSTOMERBYCNIC_UNIT_FAIL = "GET_CUSTOMERBYCNIC_UNIT_FAIL";

export const GET_ACCOUNTS_UNIT_INIT = "GET_ACCOUNTS_UNIT_INIT";
export const GET_ACCOUNTS_UNIT_SUCCESS = "GET_ACCOUNTS_UNIT_SUCCESS";
export const GET_ACCOUNTS_UNIT_FAIL = "GET_ACCOUNTS_UNIT_FAIL";

export const GET_TRANSACTIONDETAILSBYCNICDEBIT_UNIT_INIT = "GET_TRANSACTIONDETAILSBYCNICDEBIT_UNIT_INIT";
export const GET_TRANSACTIONDETAILSBYCNICDEBIT_UNIT_SUCCESS = "GET_TRANSACTIONDETAILSBYCNICDEBIT_UNIT_SUCCESS";
export const GET_TRANSACTIONDETAILSBYCNICDEBIT_UNIT_FAIL = "GET_TRANSACTIONDETAILSBYCNICDEBIT_UNIT_FAIL";

export const GET_DEBITCARDDISPUTE_BY_CNIC_INIT = "GET_DEBITCARDDISPUTE_BY_CNIC_INIT";
export const GET_DEBITCARDDISPUTE_BY_CNIC_UNIT_SUCCESS = "GET_DEBITCARDDISPUTE_BY_CNIC_UNIT_SUCCESS";
export const GET_DEBITCARDDISPUTE_BY_CNIC_UNIT_FAIL = "GET_DEBITCARDDISPUTE_BY_CNIC_UNIT_FAIL";

export const GET_DEBITCARDDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_FAIL = "GET_DEBITCARDDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_FAIL";
export const GET_DEBITCARDDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_SUCCESS = "GET_DEBITCARDDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_SUCCESS";

export const UPDATE_DEBITCARDDISPUTE_UNIT_INIT = "UPDATE_DEBITCARDDISPUTE_UNIT_INIT";
export const UPDATE_DEBITCARDDISPUTE_UNIT_SUCCESS = "UPDATE_DEBITCARDDISPUTE_UNIT_SUCCESS";
export const UPDATE_DEBITCARDDISPUTE_UNIT_FAIL = "UPDATE_DEBITCARDDISPUTE_UNIT_FAIL";

export const UPDATEANDAPPROVE_DEBITCARDDISPUTE_UNIT_INIT = "UPDATEANDAPPROVE_DEBITCARDDISPUTE_UNIT_INIT";
export const UPDATEANDAPPROVE_DEBITCARDDISPUTE_UNIT_SUCCESS = "UPDATEANDAPPROVE_DEBITCARDDISPUTE_UNIT_SUCCESS";
export const UPDATEANDAPPROVE_DEBITCARDDISPUTE_UNIT_FAIL = "UPDATEANDAPPROVE_DEBITCARDDISPUTE_UNIT_FAIL";

export const GET_TRANSACTIONDETAILSBYACCOUNTNUMBERDEBIT_UNIT_SUCCESS = "GET_TRANSACTIONDETAILSBYACCOUNTNUMBERDEBIT_UNIT_SUCCESS";
export const GET_TRANSACTIONDETAILSBYACCOUNTNUMBERDEBIT_UNIT_FAIL = "GET_TRANSACTIONDETAILSBYACCOUNTNUMBERDEBIT_UNIT_FAIL";

export const RESET_UPLOAD_FILES = "RESET_UPLOAD_FILES";
export const RESET_ALL_STATE = "RESET_ALL_STATE";

// forADC

// IRIS SEARCH
export const GET_ACCOUNTS_ADC_UNIT_SUCCESS = "GET_ACCOUNTS_ADC_UNIT_SUCCESS";
export const GET_ACCOUNTS_ADC_UNIT_FAIL = "GET_ACCOUNTS_ADC_UNIT_FAIL";

// for add NEW dispute
export const GET_TRANSACTIONDETAILSBYCNICADC_INIT = "GET_TRANSACTIONDETAILSBYCNICADC_INIT";
export const GET_TRANSACTIONDETAILSBYCNICADC_UNIT_SUCCESS = "GET_TRANSACTIONDETAILSBYCNICADC_UNIT_SUCCESS";
export const GET_TRANSACTIONDETAILSBYCNICADC_UNIT_FAIL = "GET_TRANSACTIONDETAILSBYCNICADC_UNIT_FAIL";

// For Searching ADC
export const SEARCH_ADCDISPUTE_UNIT_INIT = "SEARCH_ADCDISPUTE_UNIT_INIT";
export const SEARCH_ADCDISPUTE_UNIT_SUCCESS = "SEARCH_ADCDISPUTE_UNIT_SUCCESS";
export const SEARCH_ADCDISPUTE_UNIT_FAIL = "SEARCH_ADCDISPUTE_UNIT_FAIL";
export const RESET_ADC_DISPUTE = "RESET_ADC_DISPUTE";
export const GET_LOADER_FALSE = "GET_LOADER_FALSE";

//For Update and Approve
export const UPDATE_ADCDISPUTE_UNIT_INIT = "UPDATE_ADCDISPUTE_UNIT_INIT";
export const UPDATE_ADCDISPUTE_UNIT_SUCCESS = "UPDATE_ADCDISPUTE_UNIT_SUCCESS";
export const UPDATE_ADCDISPUTE_UNIT_FAIL = "UPDATE_ADCDISPUTE_UNIT_FAIL";

export const UPDATEANDAPPROVE_ADCDISPUTE_UNIT_INIT = "UPDATEANDAPPROVE_ADCDISPUTE_UNIT_INIT";
export const UPDATEANDAPPROVE_ADCDISPUTE_UNIT_SUCCESS = "UPDATEANDAPPROVE_ADCDISPUTE_UNIT_SUCCESS";
export const UPDATEANDAPPROVE_ADCDISPUTE_UNIT_FAIL = "UPDATEANDAPPROVE_ADCDISPUTE_UNIT_FAIL";

export const GET_ADCDISPUTE_BY_CNIC_UNIT_INIT = "GET_ADCDISPUTE_BY_CNIC_UNIT_INIT";
export const GET_ADCDISPUTE_BY_CNIC_UNIT_SUCCESS = "GET_ADCDISPUTE_BY_CNIC_UNIT_SUCCESS";
export const GET_ADCDISPUTE_BY_CNIC_UNIT_FAIL = "GET_ADCDISPUTE_BY_CNIC_UNIT_FAIL";

export const GET_ADCDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_INIT = "GET_ADCDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_INIT";
export const GET_ADCDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_SUCCESS = "GET_ADCDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_SUCCESS";
export const GET_ADCDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_FAIL = "GET_ADCDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_FAIL";

//QA MANAGER REDUCERS
export const GET_QA_MANAGER_INIT = "GET_QA_MANAGER_INIT";
export const GET_QA_MANAGER_FAIL = "GET_QA_MANAGER_FAIL";
export const GET_PENDINGFORAPPROVALQA_UNIT_INIT = "GET_PENDINGFORAPPROVALQA_UNIT_INIT";
export const GET_PENDINGFORAPPROVALQA_UNIT_SUCCESS = "GET_PENDINGFORAPPROVALQA_UNIT_SUCCESS";
export const GET_PENDINGFORAPPROVALQA_UNIT_FAIL = "GET_PENDINGFORAPPROVALQA_UNIT_FAIL";
export const SAVE_PENDINGFORDELETION_SUCCESS = "SAVE_PENDINGFORDELETION_SUCCESS";
export const SAVE_PENDINGFORDELETION_FAIL = "SAVE_PENDINGFORDELETION_FAIL";
export const RESET_ALLDISPUTEDATA = "RESET_ALLDISPUTEDATA";

//INVESTIGATION MANAGER REDUCERS
export const GET_INVESTIGATION_MANAGER_INIT = "GET_INVESTIGATION_MANAGER_INIT";
export const GET_INVESTIGATION_MANAGER_FAIL = "GET_INVESTIGATION_MANAGER_FAIL";
export const GET_PENDINGFORAPPROVAL_UNIT_INIT = "GET_PENDINGFORAPPROVAL_UNIT_INIT";
export const GET_PENDINGFORAPPROVAL_UNIT_SUCCESS = "GET_PENDINGFORAPPROVAL_UNIT_SUCCESS";
export const GET_PENDINGFORAPPROVAL_UNIT_FAIL = "GET_PENDINGFORAPPROVAL_UNIT_FAIL";
export const SAVE_APPROVAL_SUCCESS = "SAVE_APPROVAL_SUCCESS";
export const SAVE_APPROVAL_FAIL = "SAVE_APPROVAL_FAIL";
export const SAVE_REJECTION_SUCCESS = "SAVE_REJECTION_SUCCESS";
export const SAVE_REJECTION_FAIL = "SAVE_REJECTION_FAIL";
export const GET_TRANSACTIONTYPES_UNIT_INIT = "GET_TRANSACTIONTYPES_UNIT_INIT";
export const GET_TRANSACTIONTYPES_UNIT_SUCCESS = "GET_TRANSACTIONTYPES_UNIT_SUCCESS";
export const GET_TRANSACTIONTYPES_UNIT_FAIL = "GET_TRANSACTIONTYPES_UNIT_FAIL";

// forADC

// IRIS SEARCH
// export const GET_ACCOUNTS_ADC_UNIT_SUCCESS = "GET_ACCOUNTS_ADC_UNIT_SUCCESS";
// export const GET_ACCOUNTS_ADC_UNIT_FAIL = "GET_ACCOUNTS_ADC_UNIT_FAIL";

// for add NEW dispute
// export const GET_TRANSACTIONDETAILSBYCNICADC_INIT = "GET_TRANSACTIONDETAILSBYCNICADC_INIT";
// export const GET_TRANSACTIONDETAILSBYCNICADC_UNIT_SUCCESS = "GET_TRANSACTIONDETAILSBYCNICADC_UNIT_SUCCESS";
// export const GET_TRANSACTIONDETAILSBYCNICADC_UNIT_FAIL = "GET_TRANSACTIONDETAILSBYCNICADC_UNIT_FAIL";

// For Searching ADC
// export const SEARCH_ADCDISPUTE_UNIT_INIT = "SEARCH_ADCDISPUTE_UNIT_INIT";
// export const SEARCH_ADCDISPUTE_UNIT_SUCCESS = "SEARCH_ADCDISPUTE_UNIT_SUCCESS";
// export const SEARCH_ADCDISPUTE_UNIT_FAIL = "SEARCH_ADCDISPUTE_UNIT_FAIL";
// export const RESET_ADC_DISPUTE = "RESET_ADC_DISPUTE";
// export const GET_LOADER_FALSE = "GET_LOADER_FALSE";

//For Update and Approve
// export const UPDATE_ADCDISPUTE_UNIT_INIT = "UPDATE_ADCDISPUTE_UNIT_INIT";
// export const UPDATE_ADCDISPUTE_UNIT_SUCCESS = "UPDATE_ADCDISPUTE_UNIT_SUCCESS";
// export const UPDATE_ADCDISPUTE_UNIT_FAIL = "UPDATE_ADCDISPUTE_UNIT_FAIL";

// export const UPDATEANDAPPROVE_ADCDISPUTE_UNIT_INIT = "UPDATEANDAPPROVE_ADCDISPUTE_UNIT_INIT";
// export const UPDATEANDAPPROVE_ADCDISPUTE_UNIT_SUCCESS = "UPDATEANDAPPROVE_ADCDISPUTE_UNIT_SUCCESS";
// export const UPDATEANDAPPROVE_ADCDISPUTE_UNIT_FAIL = "UPDATEANDAPPROVE_ADCDISPUTE_UNIT_FAIL";

// export const GET_ADCDISPUTE_BY_CNIC_UNIT_INIT = "GET_ADCDISPUTE_BY_CNIC_UNIT_INIT";
// export const GET_ADCDISPUTE_BY_CNIC_UNIT_SUCCESS = "GET_ADCDISPUTE_BY_CNIC_UNIT_SUCCESS";
// export const GET_ADCDISPUTE_BY_CNIC_UNIT_FAIL = "GET_ADCDISPUTE_BY_CNIC_UNIT_FAIL";

// export const GET_ADCDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_INIT = "GET_ADCDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_INIT";
// export const GET_ADCDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_SUCCESS = "GET_ADCDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_SUCCESS";
// export const GET_ADCDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_FAIL = "GET_ADCDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_FAIL";
export const GET_TRANSACTIONDETAILSBYACCOUNTNUMBERADC_UNIT_SUCCESS = "GET_TRANSACTIONDETAILSBYACCOUNTNUMBERADC_UNIT_SUCCESS";
export const GET_TRANSACTIONDETAILSBYACCOUNTNUMBERADC_UNIT_FAIL = "GET_TRANSACTIONDETAILSBYACCOUNTNUMBERADC_UNIT_FAIL";

//===BBKONNECT====\\
export const GET_TRANSACTIONDETAILSBYCNICBBK_UNIT_INIT = "GET_TRANSACTIONDETAILSBYCNICBBK_UNIT_INIT";
export const GET_TRANSACTIONDETAILSBYCNICBBK_UNIT_SUCCESS = "GET_TRANSACTIONDETAILSBYCNICBBK_UNIT_SUCCESS";
export const GET_TRANSACTIONDETAILSBYCNICBBK_UNIT_FAIL = "GET_TRANSACTIONDETAILSBYCNICBBK_UNIT_FAIL";

export const GET_ACCOUNTSBBK_UNIT_INIT = "GET_ACCOUNTSBBK_UNIT_INIT";
export const GET_ACCOUNTSBBK_UNIT_SUCCESS = "GET_ACCOUNTSBBK_UNIT_SUCCESS";
export const GET_ACCOUNTSBBK_UNIT_FAIL = "GET_ACCOUNTSBBK_UNIT_FAIL";

export const GET_ACCOUNTSBYMOBILENUMBERBBK_UNIT_SUCCESS = "GET_ACCOUNTSBYMOBILENUMBERBBK_UNIT_SUCCESS";
export const GET_ACCOUNTSBYMOBILENUMBERBBK_UNIT_FAIL = "GET_ACCOUNTSBYMOBILENUMBERBBK_UNIT_FAIL";

export const GET_IRISTRANSACTIONDETAILSBYACCOUNTNUMBERBBK_UNIT_INIT = "GET_IRISTRANSACTIONDETAILSBYACCOUNTNUMBERBBK_UNIT_INIT";
export const GET_IRISTRANSACTIONDETAILSBYACCOUNTNUMBERBBK_UNIT_SUCCESS = "GET_IRISTRANSACTIONDETAILSBYACCOUNTNUMBERBBK_UNIT_SUCCESS";
export const GET_IRISTRANSACTIONDETAILSBYACCOUNTNUMBERBBK_UNIT_FAIL = "GET_IRISTRANSACTIONDETAILSBYACCOUNTNUMBERBBK_UNIT_FAIL";

export const GET_IRISTRANSACTIONDETAILSBYMOBILENUMBERBBK_UNIT_SUCCESS = "GET_IRISTRANSACTIONDETAILSBYMOBILENUMBERBBK_UNIT_SUCCESS";
export const GET_IRISTRANSACTIONDETAILSBYMOBILENUMBERBBK_UNIT_FAIL = "GET_IRISTRANSACTIONDETAILSBYMOBILENUMBERBBK_UNIT_FAIL";

export const SEARCH_BBKDISPUTE_UNIT_INIT = "SEARCH_BBKDISPUTE_UNIT_INIT";
export const SEARCH_BBKDISPUTE_UNIT_SUCCESS = "SEARCH_BBKDISPUTE_UNIT_SUCCESS";
export const SEARCH_BBKDISPUTE_UNIT_FAIL = "SEARCH_BBKDISPUTE_UNIT_FAIL";

export const RESET_BBK_DISPUTE = "RESET_BBK_DISPUTE";

export const GET_BBKDISPUTE_BY_CNIC_INIT = "GET_BBKDISPUTE_BY_CNIC_INIT";
export const GET_BBKDISPUTE_BY_CNIC_UNIT_SUCCESS = "GET_BBKDISPUTE_BY_CNIC_UNIT_SUCCESS";
export const GET_BBKDISPUTE_BY_CNIC_UNIT_FAIL = "GET_BBKDISPUTE_BY_CNIC_UNIT_FAIL";

export const GET_BBKDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_INIT = "GET_BBKDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_INIT";
export const GET_BBKDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_SUCCESS = "GET_BBKDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_SUCCESS";
export const GET_BBKDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_FAIL = "GET_BBKDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_FAIL";

export const UPDATE_BBKDISPUTE_UNIT_SUCCESS = "UPDATE_BBKDISPUTE_UNIT_SUCCESS";
export const UPDATE_BBKDISPUTE_UNIT_FAIL = "UPDATE_BBKDISPUTE_UNIT_FAIL";
export const UPDATEANDAPPROVE_BBKDISPUTE_UNIT_SUCCESS = "UPDATEANDAPPROVE_BBKDISPUTE_UNIT_SUCCESS";
export const UPDATEANDAPPROVE_BBKDISPUTE_UNIT_FAIL = "UPDATEANDAPPROVE_BBKDISPUTE_UNIT_FAIL";


export const GET_TRANSACTIONDETAILSBYACCOUNTNUMBERBBK_UNIT_SUCCESS = "GET_TRANSACTIONDETAILSBYACCOUNTNUMBERBBK_UNIT_SUCCESS";
export const GET_TRANSACTIONDETAILSBYACCOUNTNUMBERBBK_UNIT_FAIL = "GET_TRANSACTIONDETAILSBYACCOUNTNUMBERBBK_UNIT_FAIL";

export const GET_TRANSACTIONDETAILSBYMOBILENUMBERBBK_UNIT_SUCCESS = "GET_TRANSACTIONDETAILSBYMOBILENUMBERBBK_UNIT_SUCCESS";
export const GET_TRANSACTIONDETAILSBYMOBILENUMBERBBK_UNIT_FAIL = "GET_TRANSACTIONDETAILSBYMOBILENUMBERBBK_UNIT_FAIL";

// for edit user
export const EDIT_USER_INIT = "EDIT_USER_INIT";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";

//===NONAPIDISPUTES====\\
// export const GET_TRANSACTIONDETAILSBYCNICNONAPI_UNIT_INIT = "GET_TRANSACTIONDETAILSBYCNICNONAPI_UNIT_INIT";
// export const GET_TRANSACTIONDETAILSBYCNICNONAPI_UNIT_SUCCESS = "GET_TRANSACTIONDETAILSBYCNICNONAPI_UNIT_SUCCESS";
// export const GET_TRANSACTIONDETAILSBYCNICNONAPI_UNIT_FAIL = "GET_TRANSACTIONDETAILSBYCNICNONAPI_UNIT_FAIL";

// export const GET_ACCOUNTSNONAPI_UNIT_INIT = "GET_ACCOUNTSNONAPI_UNIT_INIT";
// export const GET_ACCOUNTSNONAPI_UNIT_SUCCESS = "GET_ACCOUNTSNONAPI_UNIT_SUCCESS";
// export const GET_ACCOUNTSNONAPI_UNIT_FAIL = "GET_ACCOUNTSNONAPI_UNIT_FAIL";

// export const GET_IRISTRANSACTIONDETAILSBYACCOUNTNUMBERNONAPI_UNIT_INIT = "GET_IRISTRANSACTIONDETAILSBYACCOUNTNUMBERNONAPI_UNIT_INIT";
// export const GET_IRISTRANSACTIONDETAILSBYACCOUNTNUMBERNONAPI_UNIT_SUCCESS = "GET_IRISTRANSACTIONDETAILSBYACCOUNTNUMBERNONAPI_UNIT_SUCCESS";
// export const GET_IRISTRANSACTIONDETAILSBYACCOUNTNUMBERNONAPI_UNIT_FAIL = "GET_IRISTRANSACTIONDETAILSBYACCOUNTNUMBERNONAPI_UNIT_FAIL";

// export const SEARCH_NONAPIDISPUTE_UNIT_INIT = "SEARCH_NONAPIDISPUTE_UNIT_INIT";
// export const SEARCH_NONAPIDISPUTE_UNIT_SUCCESS = "SEARCH_NONAPIDISPUTE_UNIT_SUCCESS";
// export const SEARCH_NONAPIDISPUTE_UNIT_FAIL = "SEARCH_NONAPIDISPUTE_UNIT_FAIL";

// export const RESET_NONAPI_DISPUTE = "RESET_NONAPI_DISPUTE";

// export const GET_NONAPIDISPUTE_BY_CNIC_INIT = "GET_NONAPIDISPUTE_BY_CNIC_INIT";
// export const GET_NONAPIDISPUTE_BY_CNIC_UNIT_SUCCESS = "GET_NONAPIDISPUTE_BY_CNIC_UNIT_SUCCESS";
// export const GET_NONAPIDISPUTE_BY_CNIC_UNIT_FAIL = "GET_NONAPIDISPUTE_BY_CNIC_UNIT_FAIL";

// export const GET_NONAPIDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_INIT = "GET_BBKDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_INIT";
// export const GET_NONAPIDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_SUCCESS = "GET_BBKDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_SUCCESS";
// export const GET_NONAPIDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_FAIL = "GET_BBKDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_FAIL";

// export const UPDATE_NONAPIDISPUTE_UNIT_SUCCESS = "UPDATE_NONAPIDISPUTE_UNIT_SUCCESS";
// export const UPDATEANDAPPROVE_NONAPIDISPUTE_UNIT_SUCCESS = "UPDATEANDAPPROVE_NONAPIDISPUTE_UNIT_SUCCESS";


// export const GET_TRANSACTIONDETAILSBYACCOUNTNUMBERNONAPI_UNIT_SUCCESS = "GET_TRANSACTIONDETAILSBYACCOUNTNUMBERNONAPI_UNIT_SUCCESS";
// export const GET_TRANSACTIONDETAILSBYACCOUNTNUMBERNONAPI_UNIT_FAIL = "GET_TRANSACTIONDETAILSBYACCOUNTNUMBERNONAPI_UNIT_FAIL";
// <<<<<<< HEAD

export const GET_IRISTRANSACTIONDETAILSBYCNICCC_UNIT_SUCCESS = "GET_IRISTRANSACTIONDETAILSBYCNICCC_UNIT_SUCCESS";
export const GET_IRISTRANSACTIONDETAILSBYCNICCC_UNIT_FAIL = "GET_IRISTRANSACTIONDETAILSBYCNICCC_UNIT_FAIL";
// =======
// FOR IRIS FAIL MODAL HANDLER
export const SET_MODAL_HANDLER_FAIL = "SET_MODAL_HANDLER_FAIL";
// FOR DISPUTE  MODAL HANDLER
export const SET_MODAL_FOR_DISPUTE = "SET_MODAL_FOR_DISPUTE";

// >>>>>>> Huzeifa


//SYSTEM ADMIN
export const GET_PENDINGFORDELETIONSA_UNIT_INIT = "GET_PENDINGFORDELETIONSA_UNIT_INIT";
export const GET_PENDINGFORDELETIONSA_UNIT_SUCCESS = "GET_PENDINGFORDELETIONSA_UNIT_SUCCESS";
export const GET_PENDINGFORDELETIONSA_UNIT_FAIL = "GET_PENDINGFORDELETIONSA_UNIT_FAIL";
export const SAVE_PENDINGFORDELETIONSA_SUCCESS = "SAVE_PENDINGFORDELETIONSA_SUCCESS";
export const SAVE_PENDINGFORDELETIONSA_FAIL = "SAVE_PENDINGFORDELETIONSA_FAIL";
export const SAVE_INPROCESSSA_SUCCESS = "SAVE_INPROCESSSA_SUCCESS";
export const SAVE_INPROCESSSA_FAIL = "SAVE_INPROCESSSA_FAIL";
export const SEARCH_DELETEDISPUTECASES_UNIT_INIT = "SEARCH_DELETEDISPUTECASES_UNIT_INIT";
export const SEARCH_DELETEDISPUTECASES_UNIT_SUCCESS = "SEARCH_DELETEDISPUTECASES_UNIT_SUCCESS";
export const SEARCH_DELETEDISPUTECASES_UNIT_FAIL = "SEARCH_DELETEDISPUTECASES_UNIT_FAIL";
export const RESET_SYSTEMADMINVIEW_DISPUTE = "RESET_SYSTEMADMINVIEW_DISPUTE";

export const SEARCH_GLOBALDISPUTES_UNIT_SUCCESS = "SEARCH_GLOBALDISPUTES_UNIT_SUCCESS";
export const SEARCH_GLOBALDISPUTES_UNIT_FAIL = "SEARCH_GLOBALDISPUTES_UNIT_FAIL";
export const RESET_GLOBALDISPUTE_TABLE = "RESET_GLOBALDISPUTE_TABLE";





export const GET_TRANSACTIONDETAILSBYACCOUNTNUMBERDEBITIRIS_UNIT_SUCCESS = "GET_TRANSACTIONDETAILSBYACCOUNTNUMBERDEBITIRIS_UNIT_SUCCESS";
export const GET_TRANSACTIONDETAILSBYACCOUNTNUMBERDEBITIRIS_UNIT_FAIL = "GET_TRANSACTIONDETAILSBYACCOUNTNUMBERDEBITIRIS_UNIT_FAIL";


export const SET_MODAL_FOR_CUSTOMERNOTFOUNDMODAL_DISPUTE = "SET_MODAL_FOR_CUSTOMERNOTFOUNDMODAL_DISPUTE";
export const SET_MODAL_FOR_CUSTOMERFOUNDMODAL_DISPUTE = "SET_MODAL_FOR_CUSTOMERFOUNDMODAL_DISPUTE";

export const SET_MODAL_FOR_ACCOUNTNUMBERFOUNDMODAL_DISPUTE = "SET_MODAL_FOR_ACCOUNTNUMBERFOUNDMODAL_DISPUTE";
export const SET_MODAL_FOR_ACCOUNTNUMBERNOTFOUNDMODAL_DISPUTE = "SET_MODAL_FOR_ACCOUNTNUMBERNOTFOUNDMODAL_DISPUTE";

export const SET_MODAL_FOR_MOBILENUMBERFOUNDMODAL_DISPUTE = "SET_MODAL_FOR_MOBILENUMBERFOUNDMODAL_DISPUTE";
export const SET_MODAL_FOR_MOBILENUMBERNOTFOUNDMODAL_DISPUTE = "SET_MODAL_FOR_MOBILENUMBERNOTFOUNDMODAL_DISPUTE";

// FORCLEARE SIGNUP MESSAGE
export const SIGN_UP_RESPONCE_MES_CLEARE = "SIGN_UP_RESPONCE_MES_CLEARE";


export const GET_DISPUTESTATUSGLOBAL_UNIT_SUCCESS = "GET_DISPUTESTATUSGLOBAL_UNIT_SUCCESS";
export const GET_DISPUTESTATUSGLOBAL_UNIT_FAIL = "GET_DISPUTESTATUSGLOBAL_UNIT_FAIL";

export const GET_DISPUTESTATUSSAPENDINGFORDELETION_UNIT_SUCCESS = "GET_DISPUTESTATUSSAPENDINGFORDELETION_UNIT_SUCCESS";
export const GET_DISPUTESTATUSSAPENDINGFORDELETION_UNIT_FAIL = "GET_DISPUTESTATUSSAPENDINGFORDELETION_UNIT_FAIL";



// ===>> NON APIS <<==== \\
export const GET_TRANSACTIONDETAILSBYCNICNONAPI_UNIT_INIT = "GET_TRANSACTIONDETAILSBYCNICNONAPI_UNIT_INIT";
export const GET_TRANSACTIONDETAILSBYCNICNONAPI_UNIT_SUCCESS = "GET_TRANSACTIONDETAILSBYCNICNONAPI_UNIT_SUCCESS";
export const GET_TRANSACTIONDETAILSBYCNICNONAPI_UNIT_FAIL = "GET_TRANSACTIONDETAILSBYCNICNONAPI_UNIT_FAIL";

export const GET_ACCOUNTSNONAPI_UNIT_INIT = "GET_ACCOUNTSNONAPI_UNIT_INIT";
export const GET_ACCOUNTSNONAPI_UNIT_SUCCESS = "GET_ACCOUNTSNONAPI_UNIT_SUCCESS";
export const GET_ACCOUNTSNONAPI_UNIT_FAIL = "GET_ACCOUNTSNONAPI_UNIT_FAIL";

export const GET_TRANSACTIONDETAILSBYACCOUNTNUMBERNONAPIIRIS_UNIT_SUCCESS = "GET_TRANSACTIONDETAILSBYACCOUNTNUMBERNONAPIIRIS_UNIT_SUCCESS";
export const GET_TRANSACTIONDETAILSBYACCOUNTNUMBERNONAPIIRIS_UNIT_FAIL = "GET_TRANSACTIONDETAILSBYACCOUNTNUMBERNONAPIIRIS_UNIT_FAIL";

export const RESET_NONAPI_DISPUTE = "RESET_NONAPI_DISPUTE";

export const SEARCH_NONAPIDISPUTE_UNIT_SUCCESS = "SEARCH_NONAPIDISPUTE_UNIT_SUCCESS";
export const SEARCH_NONAPIDISPUTE_UNIT_FAIL = "SEARCH_NONAPIDISPUTE_UNIT_FAIL";

export const GET_NONAPIDISPUTE_BY_CNIC_INIT = "GET_NONAPIDISPUTE_BY_CNIC_INIT";
export const GET_NONAPIDISPUTE_BY_CNIC_UNIT_SUCCESS = "GET_NONAPIDISPUTE_BY_CNIC_UNIT_SUCCESS";
export const GET_NONAPIDISPUTE_BY_CNIC_UNIT_FAIL = "GET_NONAPIDISPUTE_BY_CNIC_UNIT_FAIL";

export const GET_NONAPIDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_INIT = "GET_NONAPIDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_INIT";
export const GET_NONAPIDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_SUCCESS = "GET_NONAPIDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_SUCCESS";
export const GET_NONAPIDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_FAIL = "GET_NONAPIDISPUTESFOREDITBYCNICANDREFERENCENUMBER_UNIT_FAIL";

export const UPDATE_NONAPIDISPUTE_UNIT_SUCCESS = "UPDATE_NONAPIDISPUTE_UNIT_SUCCESS";
export const UPDATEANDAPPROVE_NONAPIDISPUTE_UNIT_SUCCESS = "UPDATEANDAPPROVE_NONAPIDISPUTE_UNIT_SUCCESS";

export const GET_DISPUTESTATUSNONAPI_UNIT_SUCCESS = "GET_DISPUTESTATUSNONAPI_UNIT_SUCCESS";
export const GET_DISPUTESTATUSNONAPI_UNIT_FAIL = "GET_DISPUTESTATUSNONAPI_UNIT_FAIL";
export const SEARCH_NDB_UNIT_FAIL = "SEARCH_NDB_UNIT_FAIL";
export const SEARCH_NDB_UNIT_SUCCESS = "SEARCH_NDB_UNIT_SUCCESS";
export const SEARCH_NDBISPUTE_UNIT_FAIL = "SEARCH_NDBISPUTE_UNIT_FAIL";
export const LOADER_REPORT = "LOADER_REPORT";

export const GET_DISPUTESTATUSND_UNIT_SUCCESS = "GET_DISPUTESTATUSND_UNIT_SUCCESS";
export const GET_DISPUTESTATUSND_UNIT_FAIL = "GET_DISPUTESTATUSND_UNIT_FAIL";

export const RESET_NEGATIVEDATABASE_DISPUTE = "RESET_NEGATIVEDATABASE_DISPUTE";

export const GET_STATUS_UNIT_SUCCESS = "GET_STATUS_UNIT_SUCCESS";
export const GET_STATUS_UNIT_FAIL = "GET_STATUS_UNIT_FAIL";

export const LOADER_REQUEST = "LOADER_REQUEST";

export const GET_ACTION_UNIT_SUCCESS = "GET_ACTION_UNIT_SUCCESS";
export const GET_ACTION_UNIT_FAIL = "GET_ACTION_UNIT_FAIL";

export const GET_HOLIDAY_UNIT_SUCCESS = "GET_HOLIDAY_UNIT_SUCCESS";
export const GET_HOLIDAY_UNIT_FAIL = "GET_HOLIDAY_UNIT_FAIL";

export const GET_CASEDECISION_UNIT_SUCCESS = "GET_CASEDECISION_UNIT_SUCCESS";
export const GET_CASEDECISION_UNIT_FAIL = "GET_CASEDECISION_UNIT_FAIL";

export const GET_TRANSACTIONCURRENCYCODE_UNIT_SUCCESS = "GET_TRANSACTIONCURRENCYCODE_UNIT_SUCCESS";
export const GET_TRANSACTIONCURRENCYCODE_UNIT_FAIL = "GET_TRANSACTIONCURRENCYCODE_UNIT_FAIL";